version: 1.0.{build}
image: Visual Studio 2017

configuration:
- Debug
- Release

before_build:
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
build:
  project: AGEproject.vcxproj
  parallel: true
  verbosity: minimal
  
